volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: interview
    external: false

services:
  postgres:
    image: docker.arvancloud.ir/postgres:16-alpine
    container_name: postgres_interview
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-interview_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_interview
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PGADMIN_DEFAULT_PORT:-5050}:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_LISTEN_PORT: 443
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  interview-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview_backend_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-interview_db}
      - DB_USER=${POSTGRES_USER:-admin}
      - DB_PASS=${POSTGRES_PASSWORD:-admin}

configs:
  project_env:
    file: ./.env
